### ISSUE TITLE
Error while grabbing EPG data from Telekom/MagentaTV

### ISSUE THREAD

**Issue by eremem** [sunsettrack4/easyepg#18] opened 2019-10-07 19:28 UTC
Tested with "BBC World","CNN International","Hamburg 1","HGTV" and "RNF". The grabber returns the following output:

```
+++ COUNTRY: GERMANY +++

Loading cookie data... OK

- DOWNLOAD PROCESS -

Checking manifest files...
5 manifest file(s) to be downloaded!

Loading manifest files...
DONE!

Creating EPG manifest file... DONE!

- FILE CREATION PROCESS -

Refreshing cookie data... OK

Retrieving Channel IDs...                            Can't use an undefined value as an ARRAY reference at cid_json.pl line 50.
Validating EPG XMLTV file... DONE!

========== EPG CREATION: WARNING/ERROR LOG ============

^
Can't use an undefined value as an ARRAY reference at ch_json2xml.pl line 91.
[ EPG ERROR ] XMLTV FILE VALIDATION FAILED DUE TO THE FOLLOWING ERRORS:
magenta.xml:1: parser error : Document is empty
, or } expected while parsing object/hash, at character offset 12 (before "\n") at epg_json2xml.pl line 95.

=======================================================

Press any key to continue...
```

When I want to edit the channel list afterward, selecting MODIFY CHANNEL LIST shows no list at all and you can see the following message:

```
New channel list saved!
Please run the grabber to add new channels to the setup modules!
```

Now if I remove the grabber, add it again and try to add any channels, most of the time I get no channel list either and it shows the following message:

```
Channel list creation aborted!
Please note that at least 1 channel must be included in channel list!

```

**Comment by sunsettrack4** [comment] 2019-10-07 20:05
This is a problem caused by the cookie, preventing the script from updating the setup correctly. I'll take a look at it asap.

**Comment by sunsettrack4** [comment] 2019-10-07 20:24
@ererem Please kindly check if @DeBaschdi 's script version fixes your problems:
https://github.com/DeBaschdi/easyepg

You can switch the version by running branch-debaschdi.sh from the script folder.

**Comment by eremem** [comment] 2019-10-07 20:40
Yes, after the switch the grabber seems to work:

```
+++ COUNTRY: GERMANY +++

Starting Proxy Server
proxy.sh started on 127.0.0.1:8000
- DOWNLOAD PROCESS -

Checking manifest files...
5 manifest file(s) to be downloaded!

Loading manifest files...
Progress [####################] 100% DONE!

Creating EPG manifest file... DONE!

- FILE CREATION PROCESS -

Validating EPG XMLTV file... DONE!

Stopping Proxy Server
proxy.sh stopped!
Press any key to continue...

```

Is there a chance that this version lands in the official branch?

Btw. in this branch, the fix from the official one would be required for TV-SPIELFILM, since I get the same error here as in #19

**Comment by sunsettrack4** [comment] 2019-10-07 20:44
Pull request re-opened: https://github.com/sunsettrack4/easyepg/pull/13

@ererem Please test your Telekom setup a few times - to make sure that everything works correctly. I'll merge the fix after positive feedback.

**Comment by eremem** [comment] 2019-10-07 20:59
As requested I've started the Telekom grabber ~10 times. I added a few random channels to my previous setup (now 20 in total) to make the tests more a real-world case. No problems were reported, everything seems to work as expected.

**Comment by sunsettrack4** [comment] 2019-10-07 21:03
Merged: https://github.com/sunsettrack4/easyepg/commit/d052abfe49f8f5df710aa810107da77d5eec8e34

**Closed as completed by sunsettrack4** 2019-10-07 21:03 UTC
Labels: bug
