### ISSUE TITLE
unknown channel-IDs when grabbing tv-spielfilm

### ISSUE THREAD

**Issue by mclenburg** [sunsettrack4/easyepg#40] opened 2020-06-01 18:30 UTC
After grabbing data from tv-spielfilm there are following lines in final log:
...
[ EPG WARNING ] Channel ID unknown: BR
[ EPG WARNING ] Channel ID unknown: MDR
[ EPG WARNING ] Channel ID unknown: N3
[ EPG WARNING ] Channel ID unknown: RBB
[ EPG WARNING ] Channel ID unknown: SWR
[ EPG WARNING ] Channel ID unknown: WDR

Result is, there is no data readable for these channels by tvheadend.

**Comment by DeBaschdi** [comment] 2020-06-02 02:26
TV-Spielfilm has new channel id's for all third programs. If you have not activated rytec id, you have to reassign the new ID'S to tvheadend.

**Comment by stueble** [comment] 2020-06-02 22:57
Hi. I have the same problem and I have no clue what to do to fix that: I activated rytec id, but the warnings still appear. However, the resulting tv-spielfilm.xml contains the corresponding epg entries, e.g., for WDR. But merging does not work. The customized XML file does not contain those channels where tv-spielfilm created warnings. I assume that the merging is based on the chosen channel names, e.g., "WDR Köln", but tv-spielfilm.xml only contains entries for WDR. Anything I can do?

**Comment by DeBaschdi** [comment] 2020-06-03 03:14
Just open tvs channel selector, check wdr-köln, save it.
grab tvs, open customized setup, check wdr-köln, start customized setup.
If u have activated rytec id, assign wdr.de in tvh.

**Comment by stueble** [comment] 2020-06-03 16:16
Hi. I started from a fresh install, v0.4.3. after selecting (only) "WDR Köln" and invoking the tvs grabber, I already get the warning "Channel ID unknown: WDR", but the xml file includes all EPG data. However, after starting the customized setup, the resulting xml file is empty, except of the channel info of WDR.de itself. So, the EPG information is still filtered out by the customization script.

**Comment by DeBaschdi** [comment] 2020-06-04 03:01
you're right, unfortunately I can't find a working workaround right now

**Comment by stueble** [comment] 2020-06-04 07:11
Can you explain what the problem is? Maybe I have an idea.

**Comment by DeBaschdi** [comment] 2020-06-05 12:59
please try the new Hotfix, updtate this script, select wdr ect again and reassign it to your channels.

**Closed as completed** 2020-06-05 18:58 UTC

**Comment by stueble** [comment] 2020-06-06 01:17
Hi DeBaschdi, seems to work, many thanks!
